baseURL = 'https://wonderful-smoke-0bac49003.4.azurestaticapps.net'
languageCode = 'en'
title = 'Theapersnakes'
theme = "infinity"
publishDir = "public"


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/hero/logo-white-small.png"
home = "Home"
bio = "Bio"
video = "Videos"
cover = "Cover Art"
music = "Music"
contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
image = "images/hero/logo-black.png"
subtitle = "Singer Songwriters"
btnText = "Get Started"

# counter
disableCountdown = false
countdownYear = "2022"
countdownMonth = "12"
countdownDay = "31"

# Bio Section
[params.bio]
enable = true
heading = "Bio"
content = """

ThePapersnakes is the songwriting and performing partnership of Paul Kerr (guitar) and Chris Ward (bass).  
  

The pair first met when battling to monopolise the CD player at house parties.  

Armed with a strong set of shared influences they started writing together in 2007.  

Their influences span rock,   pop,   funk,   reggae and ska and a love for classic disco.  

The band's style features bold guitar parts and memorable basslines to create their distinctive,   full-of-energy sound.  Their performances always keep true to their "light and shade" motto.  This results in a mix of up-tempo bangers and stripped-back slow songs.  

Their covers list reflects their varied influences. From Prince to Paul Weller,   from Bob Marley to Amy Winehouse.  

From the start,   the ThePapersnakes have focused on writing and performing original material. Their songs have featured in every gig in their extensive playing history.  

They often now play shows which are only original songs.  

The band do all their own studio recording and production in their "2Snakes" studio. They have released many of their songs on streaming platforms and on CD.  
 
In 2021 they ran a successful crowdfunding project to fund their first vinyl release. This nine song album of original songs,   named "Volume One",   is due to land in September 2022.  

They often play live on local radio. This has ranged from small community radio stations to some BBC stations.  

They are very active playing on their local music scene,   often at large organised events. In May 2022 they played the main stage at the Rickmansworth Festival to an audience of more than 2,  500.  

ThePapersnakes perform either as a duo,   using a variety of technology to expand their sound. or as a three-piece band with drummer Andy Vellacott.  

The band also produce their own cover artwork. One piece was accepted for an exhibition outside the central St. Albans Arts Centre in 2022.  

"""
[[params.bio.sliderItem]]
image = "images/photos/chris-1.jpg"
[[params.bio.sliderItem]]
image = "images/photos/paul-1.jpg"
[[params.bio.sliderItem]]
image = "images/photos/papersnakes high st.jpg"
[[params.bio.sliderItem]]
image = "images/photos/street.jpg"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Video Section
[params.video]
enable = true
title = "Videos"
subtitle = "Something for you eyes while your ears are busy."

[[params.video.videoItem]]
youtube = "rjWnV538feA"
title = "Glimmer of Hope"
#description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.video.videoItem]]
youtube = "pobO-P0V6yQ"
title = "Red Jeans"
#description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "tCvgoiFawVU"
title = "Green Unpleasant"
#description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "BYUVpkzAA-8"
title = "Beast in the East"
#description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "gf3axNejLBA"
title = "On My Own"
#description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "YUtuutXIx5s"
title = "Hold On"
#description = "Blah, blah, blah ..."
delay = "0.5s"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# Music Section
[params.music]
enable = true
title = "Music"
subtitle = "ThePapersnakes is dedicated to creating new songs."

[[params.music.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/sets/volume-one-1"
title = "VOLUME ONE"
description = """Our first album, available on heavyweight red vinyl!  
Produced thanks to our Kickstarter campaign."""
delay = "0.3s"

[[params.music.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/dont-shout-it"
single = true
title = "Don't Shout It"
delay = "0.3s"

[[params.music.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/hero"
single = true
title = "Hero"
description = """Written to a brief for a local festival on the theme 'Heros'.  
A collaboration with local singer/songwriter Beth Hedges."""
delay = "0.3s"

[[params.music.songItem]]
spotify_id = "6BkPm15IUhmTaUk93eHS1p"
spotify_type = "album"
title = "Too Much Too Young"
description = "Cover of The Specials classic"
delay = "0.3s"

[[params.music.songItem]]
spotify_id = "76INDInePPGw5330pHBioi"
spotify_type = "album"
title = "Green Unpleasant"
description = "Extended version"
delay = "0.3s"

#[[params.music.songItem]]
#spotify_id = "3JUg7f0maidbFHYDEFE2og"
#spotify_type = "album"
#title = "Bare Back Reindeer"
#description = "Blah, blah, blah ..."
#delay = "0.3s"

# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

[params.cover]
enable = true
title = "VOLUME ONE - Singles Covers"
description = "Blah, blah, blah ..."
delay = "0.5s"



# ---------------------------------------------------------------------------------
[[params.cover.coverItem]]
title = "Round and Round"
description = "Digital & physical collage, available as framed print.  Layered '3D' version available."
image = "images/covers/R&R 300 DPI - 3000 x 3000 px.jpeg"
delay = "0.5s"

  [[params.cover.coverItem.thumbnail]]
  title = "Round and Round"
  description = "Layered '3D' in deep box frame."
  image = "images/covers/thumbs/1.jpg"
  delay = "0.5s"

  [[params.cover.coverItem.thumbnail]]
  description = "Framed print and Layered '3D' in deep box frame."
  image = "images/covers/thumbs/2.jpg"
  delay = "0.5s"

  [[params.cover.coverItem.thumbnail]]
  title = "Round and Round"
  description = "Layered '3D' in deep box frame."
  image = "images/covers/thumbs/3.jpg"
  delay = "0.5s"

# ---------------------------------------------------------------------------------

[[params.cover.coverItem]]
title = "All I Want Is"
description = "Original photograph. Moorgate, London."
image = "images/covers/All I Want Is.jpeg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Hold On"
description = "Original photograph. London Wall, London"
image = "images/covers/Hold On.png"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Red Jeans"
description = "Digital collage - features the background design used on the VOLUME ONE cover."
image = "images/covers/Red Jeans.png"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Beast in the East"
description = "Digitial collage - '2016 : Syria | Trump | Brexit'"
image = "images/covers/Beast in the East.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Green Unpleasant"
description = "(Single version) - Features background still from song video."
image = "images/covers/cover-2000px-300dpi.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Fields of Dreams"
description = "Internet stock image background"
image = "images/covers/Fields of Dreams.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Glimmer of Hope"
description = "Internet stock image background"
image = "images/covers/Glimmer of Hope 3112x3009.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "On My Own"
description = "Digital Collage"
image = "images/covers/On My Own.jpeg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Dont Shout It"
description = "AI + Digital Collage"
image = "images/covers/Dont Shout It - 300dpi 3000x3000px.jpg"
delay = "0.5s"


[[params.cover.coverItem]]
title = "Back Back Reindeer"
description = "Digital Collage"
image = "images/covers/Back Back Reindeer - 300dpi - 3000x3000px.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Too Much Too Young"
description = "Digitally Manipulated photograph"
image = "images/covers/Too Much Too Young.jpg"
delay = "0.5s"

[[params.cover.coverItem]]
title = "Green Unpleasant - Extended"
description = "Digitally Manipulated photograph"
image = "images/covers/Extended Version (Lo Res version) 3000x3000 300dpi.jpg"
delay = "0.5s"



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Links
[params.links]
enable = true
bg = "images/call-to-action.jpg"
social = [
  { name = "Facebook", url = "https://www.facebook.com/thepapersnakesmusic", icon = "fab fa-facebook" },
  { name = "Youtube", url = "https://www.youtube.com/@thepapersnakes8534", icon = "fab fa-youtube" },
  { name = "Soundcloud", url = "https://soundcloud.com/thepapersnakes", icon = "fab fa-soundcloud" },
  { name = "Spotify", url = "https://open.spotify.com/artist/4LazGuOAEFN0SfH83mDJa4", icon = "fab fa-spotify" },
  { name = "Apple Music", url = "https://itunes.apple.com/us/artist/thepapersnakes/327364903", icon = "fab fa-apple" },
  { name = "Twitter", url = "https://twitter.com/thepapersnakes?lang=en", icon = "fab fa-twitter" },
  { name = "Instagram", url = "https://www.instagram.com/thepapersnakes/?hl=en", icon = "fab fa-instagram" },

]

[params.contact]
enable = true
title = "Get In Touch"
subtitle = "Drop us a message!"
email="info@thepapersnakes.co.uk"