baseURL = 'https://nice-beach-096bc3903.4.azurestaticapps.net'
languageCode = 'en'
title = 'Theapersnakes'
theme = "infinity"
publishDir = "public"



# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
about = "About"
video = "Video"
song = "Song"
contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
title = "BRING YOUR PRODUCT TO LIGHT"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
btnText = "Get Started"

# counter
disableCountdown = false
countdownYear = "2022"
countdownMonth = "12"
countdownDay = "31"

# About Section
[params.about]
enable = true
heading = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur."

[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Video Section
[params.video]
enable = true
title = "Our Videos"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

[[params.video.videoItem]]
youtube = "rjWnV538feA"
title = "Glimmer of Hope"
description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.video.videoItem]]
youtube = "pobO-P0V6yQ"
title = "Red Jeans"
description = "Blah, blah, blah ..."
delay = "0.6s"

[[params.video.videoItem]]
youtube = "tCvgoiFawVU"
title = "Green Unpleasant"
description = "Blah, blah, blah ..."
delay = "0.9s"

[[params.video.videoItem]]
youtube = "BYUVpkzAA-8"
title = "Beat in the East"
description = "Blah, blah, blah ..."
delay = "1.2s"

[[params.video.videoItem]]
youtube = "gf3axNejLBA"
title = "On My Own"
description = "Blah, blah, blah ..."
delay = "1.5s"

[[params.video.videoItem]]
youtube = "YUtuutXIx5s"
title = "Hold On"
description = "Blah, blah, blah ..."
delay = "1.8"



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# Song Section
[params.song]
enable = true
title = "Our Songs"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

[[params.song.songItem]]
title = "Glimmer of Hope"
description = "Blah, blah, blah ..."
delay = "0.3s"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# Call to Action Section
[params.cta]
enable = true
bg = "images/call-to-action.jpg"
title = "Subscribe to our mailing list"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

[params.contact]
enable = true
title = "Get In Touch"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
