baseURL = 'https://wonderful-smoke-0bac49003.4.azurestaticapps.net'
languageCode = 'en'
title = 'Theapersnakes'
theme = "infinity"
publishDir = "public"


# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/hero/logo-white-small.png"
home = "Home"
bio = "Bio"
video = "Videos"
song = "Songs"
contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
image = "images/hero/logo-black.png"
subtitle = "Singer Songwriters"
btnText = "Get Started"

# counter
disableCountdown = false
countdownYear = "2022"
countdownMonth = "12"
countdownDay = "31"

# Bio Section
[params.bio]
enable = true
heading = "Bio"
# description = "ThePapersnakes is the songwriting and performing partnership of Paul Kerr (guitar) and Chris Ward (bass).The pair first met when battling to monopolise the CD player at house parties. Armed with a strong set of shared influences they started writing together in 2007. Their influences span rock, pop, funk, reggae and ska and a love for classic disco.The band's style features bold guitar parts and memorable basslines to create their distinctive, full-of-energy sound.  Their performances always keep true to their "light and shade" motto.  This results in a mix of up-tempo bangers and stripped-back slow songs.Their covers list reflects their varied influences. From Prince to Paul Weller, from Bob Marley to Amy Winehouse.From the start, the ThePapersnakes have focused on writing and performing original material. Their songs have featured in every gig in their extensive playing history.They often now play shows which are only original songs.The band do all their own studio recording and production in their "2Snakes" studio. They have released many of their songs on streaming platforms and on CD.In 2021 they ran a successful crowdfunding project to fund their first vinyl release. This nine song album of original songs, named "Volume One", is due to land in September 2022. They often play live on local radio. This has ranged from small community radio stations to some BBC stations.They are very active playing on their local music scene, often at large organised events. In May 2022 they played the main stage at the Rickmansworth Festival to an audience of more than 2,500. ThePapersnakes perform either as a duo, using a variety of technology to expand their sound. or as a three-piece band with drummer Andy Vellacott.The band also produce their own cover artwork. One piece was accepted for an exhibition outside the central St. Albans Arts Centre in 2022."

[[params.bio.sliderItem]]
image = "images/photos/chris-1.jpg"
[[params.bio.sliderItem]]
image = "images/photos/paul-1.jpg"
[[params.bio.sliderItem]]
image = "images/photos/papersnakes high st.jpg"
[[params.bio.sliderItem]]
image = "images/photos/street.jpg"


# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------

# Video Section
[params.video]
enable = true
title = "Our Videos"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

[[params.video.videoItem]]
youtube = "rjWnV538feA"
title = "Glimmer of Hope"
description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.video.videoItem]]
youtube = "pobO-P0V6yQ"
title = "Red Jeans"
description = "Blah, blah, blah ..."
delay = "0.5s"


[[params.video.videoItem]]
youtube = "tCvgoiFawVU"
title = "Green Unpleasant"
description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "BYUVpkzAA-8"
title = "Beat in the East"
description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "gf3axNejLBA"
title = "On My Own"
description = "Blah, blah, blah ..."
delay = "0.5s"

[[params.video.videoItem]]
youtube = "YUtuutXIx5s"
title = "Hold On"
description = "Blah, blah, blah ..."
delay = "0.5s"




# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# Song Section
[params.song]
enable = true
title = "Our Songs"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"

[[params.song.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/sets/volume-one-1"
title = "VOLUME ONE"
description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.song.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/dont-shout-it"
single = true
title = "Don't Shout It"
description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.song.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/too-much-too-young-1"
single = true
title = "Too Much Too Young"
description = "Blah, blah, blah ..."
delay = "0.3s"

[[params.song.songItem]]
soundcloud_url = "https://soundcloud.com/thepapersnakes/hero"
single = true
title = "Hero"
description = "Blah, blah, blah ..."
delay = "0.3s"

# [[params.song.songItem]]
# spotify_url = "https://open.spotify.com/track/3JUg7f0maidbFHYDEFE2og"
# title = "Bare Back Reindeer"
# description = "Blah, blah, blah ..."
# delay = "0.3s"



# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------


# Call to Action Section
[params.cta]
enable = true
bg = "images/call-to-action.jpg"
title = "Subscribe to our mailing list"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

[params.contact]
enable = true
title = "Get In Touch"
subtitle = "Drop us a message!"