baseURL = "https://demo.gethugothemes.com/infinity/site/"
languageCode = "en-us"
title = "Infinity | Comming Soon Hugo Template By Themefisher"
theme = "infinity-hugo"
removePathAccents = true





# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Home"
bio = "Bio"
music = "Music"
contact = "Contact"

# Hero Area
[params.hero]
enable = true
bg = "images/header-bg.jpg"
title = "BRING YOUR PRODUCT TO LIGHT"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
btnText = "Get Started"

# counter
disableCountdown = false
countdownYear = "2022"
countdownMonth = "12"
countdownDay = "31"

# Bio Section
[params.bio]
enable = true
heading = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur."

[[params.bio.sliderItem]]
image = "images/bio/1.jpg"
[[params.bio.sliderItem]]
image = "images/bio/2.jpg"
[[params.bio.sliderItem]]
image = "images/bio/3.jpg"
[[params.bio.sliderItem]]
image = "images/bio/2.jpg"


# Service Section
[params.music]
enable = true
title = "Find Better Solutions Build Better Products"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"
[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-strategy"
title = "Fully Responsive"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "0s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-circle-compass"
title = "Speed Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "0.2s"

[[params.music.songItem]]
icon = "tf-anchor2"
title = "Tons of Feature"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "0.4s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Fully SEO Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "0.6s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-strategy"
title = "Fully Responsive"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "0.8s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-circle-compass"
title = "Speed Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "1s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-anchor2"
title = "Tons of Feature"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "1.2s"

[[params.music.songItem]]
# give icon(themefisher icon font), title, description
# more bio themefisher icon font visit https://github.com/themefisher/themefisher-font
# use delay for reveal items one by one
icon = "tf-globe"
title = "Fully SEO Optimized"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
delay = "1.5s"


# Call to Action Section
[params.links]
enable = true
bg = "images/call-to-action.jpg"
title = "Subscribe to our mailing list"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
social = [
  { name = "Twitter", url = "https://twitter.com/thepapersnakes?lang=en", icon = "fab fa-twitter" },
  { name = "Youtube", url = "https://www.youtube.com/@thepapersnakes8534", icon = "fab fa-youtube" },
  { name = "Soundcloud", url = "https://soundcloud.com/thepapersnakes", icon = "fab fa-soundcloud" },
  { name = "Spotify", url = "https://open.spotify.com/artist/4LazGuOAEFN0SfH83mDJa4", icon = "fab fa-spotify" },
  { name = "Apple Music", url = "https://itunes.apple.com/us/artist/thepapersnakes/327364903", icon = "fab fa-apple" },
  { name = "Amazon", url = "https://amazon.co.uk/music/player/artists/B002LF141G/thepapersnakes?marketplaceId=A1F83G8C2ARO7P&musicTerritory=GB&ref=dm_sh_IPQyOT2B6iyQnHSCHH9OscCeZ", icon = "fab fa-amazon" },
  { name = "Facebook", url = "https://www.facebook.com/thepapersnakesmusic", icon = "fab fa-facebook" },
  { name = "Instagram", url = "hthttps://www.instagram.com/thepapersnakes/?hl=en", icon = "fab fa-instagram" },

]


[params.contact]
enable = true
title = "Get In Touch"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
